apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
type: Opaque
data:
  discord_token: TVRNNE16YzBPRFl5T1RFeE56a3pNVFl5TVEuR0dXSy0xLkpFazVvNGFuQThZOWp3LWVtTlBEZURxNWRkT2hYYy1NMFU2OENR
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-attbot
  template:
    metadata:
      labels:
        app: discord-attbot
    spec:
      containers:
        - name: discord-attbot
          image: your-dockerhub-username/discord-attbot:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: discord_token
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"